### ISSUE TITLE
applyTemplates vs. pathTemplate vs. contentTemplate

### ISSUE THREAD

**Issue by doggy8088** [wellwind/ngtw19-schematics-workshop#7]
- applyTemplates
  - [Angular - Schematics for Libraries](https://angular.io/guide/schematics-for-libraries)
- pathTemplate & contentTemplate
  - [Build artifacts for @angular-devkit/schematics](https://github.com/angular/angular-devkit-schematics-builds#provided-operators)

**Comment by doggy8088** [comment]
`applyTemplates` 原始碼:

- https://github.com/angular/angular-devkit-schematics-builds/blob/f347ea464ece78e807051f4dbe6aa8a24f156c73/src/rules/template.js#L124-L136

**Comment by wellwind** [comment]
have updated README.md
